# FILE: codemagic.yaml (VERSI DIPERBAIKI)

workflows:
  android-app-build:
    name: Build ZHRecorder APK
    
    # Minta mesin Linux standar, lebih umum untuk build Android
    #instance_type: linux
    
    # Definisikan variabel lingkungan yang dibutuhkan
    environment:
      # Kita akan menggunakan grup variabel 'android-sdk'
      # Ini akan secara otomatis mengatur path seperti $ANDROID_SDK_ROOT
      groups:
        - android-sdk
      
      # PERBAIKAN: Definisikan versi Java yang kita butuhkan
      # Sesuai dengan 'JavaVersion.VERSION_1_8' di build.gradle-mu
      vars:
        JAVA_HOME: /usr/lib/jvm/java-1.8.0-openjdk-amd64

    scripts:
      - name: Set up local properties
        script: | 
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
          
      - name: Build APK with Gradle
        script: | 
          # Pindah ke direktori root proyekmu
          cd $CM_BUILD_DIR
          # Beri izin eksekusi pada Gradle wrapper
          chmod +x ./gradlew
          # Jalankan build
          ./gradlew assembleDebug --no-daemon
          
    artifacts:
      # Cari .apk di dalam direktori build/app/
      - app/build/outputs/apk/**/*.apk